company:
  email: "infor@framgia.com"
image:
  size:
    category_width: 340
    category_height: 224
    avatar_width: 80
    avatar_height: 80
    food_size: "750x223"
    food_edit: "100x100"
    food_index: "200x100"
    food_show: "300x200"
paginate:
  per_page: 3
